version: '3.8'
services:
  app:
    build: ./app/
    depends_on:
      - db
    volumes:
      - "./app:/usr/src/app"

  db:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=Valentin
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=lab1
    ports:
      - '5432:5432'